"""empty message

Revision ID: 5abb24ad9344
Revises: e6b161e18b47
Create Date: 2022-07-11 19:31:48.003136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abb24ad9344'
down_revision = 'e6b161e18b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('target', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'target')
    # ### end Alembic commands ###
